[project]
name = "pokemontcgp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "streamlit>=1.53.1",
    "streamlit-echarts>=0.4.0",
    "requests>=2.32.3",
]
